<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260607121857 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, customer_note TEXT DEFAULT NULL, customer_id INT NOT NULL, service_id INT NOT NULL, business_id INT NOT NULL, invoice_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE38F8449395C3F3 ON appointment (customer_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844ED5CA9E6 ON appointment (service_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844A89DB457 ON appointment (business_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE38F8442989F1FD ON appointment (invoice_id)');
        $this->addSql('CREATE TABLE artisan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, siret VARCHAR(14) NOT NULL, office_address VARCHAR(255) DEFAULT NULL, is_approved BOOLEAN NOT NULL, ownership_document VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, business_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3C600AD3A76ED395 ON artisan (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3C600AD3A89DB457 ON artisan (business_id)');
        $this->addSql('CREATE TABLE artisan_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(100) DEFAULT NULL, slug VARCHAR(120) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6CC8B6A6989D9B62 ON artisan_category (slug)');
        $this->addSql('CREATE TABLE business (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, headline VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, payment_methods JSON DEFAULT NULL, contact_number VARCHAR(30) DEFAULT NULL, office_address VARCHAR(255) DEFAULT NULL, working_hours JSON DEFAULT NULL, reply_delay VARCHAR(100) DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D36E3812469DE2 ON business (category_id)');
        $this->addSql('CREATE TABLE calendar_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, is_availability BOOLEAN NOT NULL, artisan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57FA09C95ED3C7B7 ON calendar_event (artisan_id)');
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_blocked BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT NOT NULL, business_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E99395C3F3 ON conversation (customer_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E9A89DB457 ON conversation (business_id)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, home_address VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E09A76ED395 ON customer (user_id)');
        $this->addSql('CREATE TABLE customer_favorite_business (customer_id INT NOT NULL, business_id INT NOT NULL, PRIMARY KEY (customer_id, business_id))');
        $this->addSql('CREATE INDEX IDX_B6958BD49395C3F3 ON customer_favorite_business (customer_id)');
        $this->addSql('CREATE INDEX IDX_B6958BD4A89DB457 ON customer_favorite_business (business_id)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) DEFAULT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A769395C3F3 ON document (customer_id)');
        $this->addSql('CREATE TABLE invoice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(50) NOT NULL, amount NUMERIC(8, 2) NOT NULL, issued_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pdf_path VARCHAR(255) DEFAULT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9065174496901F54 ON invoice (number)');
        $this->addSql('CREATE INDEX IDX_906517449395C3F3 ON invoice (customer_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_read BOOLEAN NOT NULL, attachment VARCHAR(255) DEFAULT NULL, sender_id INT NOT NULL, conversation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, content TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, punctuality_rating INT DEFAULT NULL, quality_rating INT DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_type VARCHAR(255) NOT NULL, appointment_id INT NOT NULL, author_id INT NOT NULL, target_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794381C6E5B533F9 ON review (appointment_id)');
        $this->addSql('CREATE INDEX IDX_794381C6F675F31B ON review (author_id)');
        $this->addSql('CREATE INDEX IDX_794381C6158E0B66 ON review (target_id)');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, duration INT NOT NULL, price NUMERIC(8, 2) NOT NULL, location VARCHAR(255) NOT NULL, faq JSON DEFAULT NULL, business_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E19D9AD2A89DB457 ON service (business_id)');
        $this->addSql('CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stripe_subscription_id VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL, current_period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, plan VARCHAR(50) NOT NULL, artisan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A3C664D3B5DBB761 ON subscription (stripe_subscription_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A3C664D35ED3C7B7 ON subscription (artisan_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(30) DEFAULT NULL, is_verified BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8449395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8442989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE artisan ADD CONSTRAINT FK_3C600AD3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE artisan ADD CONSTRAINT FK_3C600AD3A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business ADD CONSTRAINT FK_8D36E3812469DE2 FOREIGN KEY (category_id) REFERENCES artisan_category (id)');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C95ED3C7B7 FOREIGN KEY (artisan_id) REFERENCES artisan (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E99395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_favorite_business ADD CONSTRAINT FK_B6958BD49395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer_favorite_business ADD CONSTRAINT FK_B6958BD4A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A769395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6E5B533F9 FOREIGN KEY (appointment_id) REFERENCES appointment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6158E0B66 FOREIGN KEY (target_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D35ED3C7B7 FOREIGN KEY (artisan_id) REFERENCES artisan (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F8449395C3F3');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844ED5CA9E6');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844A89DB457');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F8442989F1FD');
        $this->addSql('ALTER TABLE artisan DROP CONSTRAINT FK_3C600AD3A76ED395');
        $this->addSql('ALTER TABLE artisan DROP CONSTRAINT FK_3C600AD3A89DB457');
        $this->addSql('ALTER TABLE business DROP CONSTRAINT FK_8D36E3812469DE2');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C95ED3C7B7');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E99395C3F3');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9A89DB457');
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E09A76ED395');
        $this->addSql('ALTER TABLE customer_favorite_business DROP CONSTRAINT FK_B6958BD49395C3F3');
        $this->addSql('ALTER TABLE customer_favorite_business DROP CONSTRAINT FK_B6958BD4A89DB457');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A769395C3F3');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_906517449395C3F3');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6E5B533F9');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F675F31B');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6158E0B66');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD2A89DB457');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D35ED3C7B7');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE artisan');
        $this->addSql('DROP TABLE artisan_category');
        $this->addSql('DROP TABLE business');
        $this->addSql('DROP TABLE calendar_event');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE customer_favorite_business');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
